
name: CI Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      submodule:
        description: The directory of the submodule, if this workflow is being called on a submodule
        required: true
        type: string

jobs:   
  build-modern:
    name: U-Boot for MiyooCFW (musl)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-musl:master
    steps:
    - run: echo "submodule ${{ inputs.submodule }} on ${{ github.event }}"
    - uses: actions/checkout@v3
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    # ARCH=arm and CROSS_COMPILE=arm-buildroot-linux-musleabi- env props are set in the docker image
    - name: configure
      run: |
        cd ${{ inputs.submodule || '.' }} ; apt update && apt install -y libpython3-dev python3-distutils bison flex
        make miyoo_defconfig 
    - name: build
      run: cd ${{ inputs.submodule || '.' }} && make
    - uses: actions/upload-artifact@v3
      with:
        name: U-Boot (musl)
        path: ${{ inputs.submodule || '.' }}/u-boot-sunxi-with-spl.bin
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  build-legacy:
    name: U-Boot for MiyooCFW (uClibc)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-uclibc:master
    steps:
    - run: echo "submodule ${{ inputs.submodule }} on ${{ github.event }}"
    - uses: actions/checkout@v3
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    # ARCH=arm and CROSS_COMPILE=arm-miyoo-linux-uclibcgnueabi- env props are set in the docker image
    - name: configure
      run: |
        cd ${{ inputs.submodule || '.' }} ; apt update && apt install -y libpython3-dev python3-distutils
        make miyoo_defconfig 
    - name: build
      run: cd ${{ inputs.submodule || '.' }} && make
    - uses: actions/upload-artifact@v3
      with:
        name: U-Boot (uClibc)
        path: ${{ inputs.submodule || '.' }}/u-boot-sunxi-with-spl.bin
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
